# Generated by Django 2.0.5 on 2018-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일시')),
                ('subject', models.CharField(blank=True, help_text='200자', max_length=200, null=True, verbose_name='제목')),
                ('context', models.TextField(blank=True, null=True, verbose_name='내용')),
            ],
            options={
                'db_table': 'main',
                'verbose_name': '메인',
                'verbose_name_plural': '메인',
            },
        ),
    ]
