# Generated by Django 2.0.5 on 2018-06-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180531_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_file',
            field=models.TextField(blank=True, null=True, verbose_name='이미지파일'),
        ),
    ]
