# Generated by Django 2.0.5 on 2018-06-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180607_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_file',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
