# Generated by Django 2.0.6 on 2018-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180903_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('SERVER', 'SERVER'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('JAVA', 'JAVA'), ('SPRING', 'SPRING'), ('FRONT', 'FRONT'), ('DATABASE', 'DATABASE'), ('WEB', 'WEB'), ('ELASTIC SEARCH', 'ELASTIC SEARCH')], max_length=200, null=True, verbose_name='카테고리'),
        ),
    ]
