# Generated by Django 2.0.6 on 2018-10-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20180913_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일시')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '게임',
                'verbose_name': '게임',
                'db_table': 'game',
            },
        ),
    ]
