# Generated by Django 2.0.6 on 2019-01-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
