# Generated by Django 2.0.6 on 2020-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정 일시')),
                ('ref_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='일자')),
                ('pattern_type', models.CharField(blank=True, choices=[('powerball_even_odd', '파워볼 홀짝'), ('powerball_under_over', '파워볼 언더오버'), ('even_odd', '일반 홀짝'), ('under_over', '일반 언더오버')], db_index=True, max_length=200, null=True, verbose_name='패턴 타입')),
                ('pattern_num', models.SmallIntegerField(db_index=True, default=10, verbose_name='패턴 글자수')),
                ('pattern_string', models.CharField(blank=True, max_length=200, null=True, verbose_name='패턴 문자열')),
                ('pattern_count', models.SmallIntegerField(default=10, verbose_name='패턴 수')),
            ],
            options={
                'verbose_name': '패턴분석',
                'verbose_name_plural': '패턴분석',
                'db_table': 'analytics_pattern',
            },
        ),
        migrations.AlterIndexTogether(
            name='analyticspattern',
            index_together={('ref_date', 'pattern_type', 'pattern_num')},
        ),
    ]
