# Generated by Django 2.0.6 on 2020-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200609_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticspattern',
            name='opposite_count',
            field=models.SmallIntegerField(default=10, verbose_name='반대 패턴 수'),
        ),
        migrations.AddField(
            model_name='analyticspattern',
            name='opposite_string',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='반대 패턴 문자열'),
        ),
    ]
