# Generated by Django 2.0.6 on 2020-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200609_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticspattern',
            name='ref_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='일자'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticspattern',
            unique_together={('ref_date', 'pattern_type', 'pattern_num', 'pattern_string')},
        ),
    ]
